"""add_organization_features

Revision ID: b9b038acd1ce
Revises: 1f1cde99d636
Create Date: 2025-11-11 00:22:56.560120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b038acd1ce'
down_revision: Union[str, None] = '1f1cde99d636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('size', sa.String(length=50), nullable=False, server_default='startup'))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    op.add_column('organizations', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('subscription_plan', sa.String(length=50), nullable=False, server_default='free'))
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='active'))
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('active_organization_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['active_organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_organization_id')
    op.drop_column('organizations', 'trial_ends_at')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'subscription_plan')
    op.drop_column('organizations', 'billing_email')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'size')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'website')
    # ### end Alembic commands ###
