"""Add audit trail system with comprehensive logging

Revision ID: 1e71c9e38a78
Revises: 7f8a9b2c3d4e
Create Date: 2025-11-15 21:52:24.069511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e71c9e38a78'
down_revision: Union[str, None] = '7f8a9b2c3d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audio_files_organization_id'), 'audio_files', ['organization_id'], unique=False)
    op.create_index('ix_audio_org_type', 'audio_files', ['organization_id', 'file_type'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_organization_id'), 'conversation_sessions', ['organization_id'], unique=False)
    op.create_index('ix_sessions_org_status', 'conversation_sessions', ['organization_id', 'status'], unique=False)
    op.create_index('ix_documents_org_status', 'documents', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.alter_column('organizations', 'size',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'tier_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'max_organizations_per_user',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'max_organizations_allowed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'max_organizations_allowed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('organizations', 'max_organizations_per_user',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('organizations', 'tier_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('organizations', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.alter_column('organizations', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=False)
    op.alter_column('organizations', 'size',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'startup'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_org_status', table_name='documents')
    op.drop_index('ix_sessions_org_status', table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_organization_id'), table_name='conversation_sessions')
    op.drop_index('ix_audio_org_type', table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_organization_id'), table_name='audio_files')
    # ### end Alembic commands ###